//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MessagePacket.proto
// Note: requires additional types generated from: MessageID.proto
// Note: requires additional types generated from: MessageRetCode.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagePacket")]
  public partial class MessagePacket : global::ProtoBuf.IExtensible
  {
    public MessagePacket() {}
    
    private Protocol.MessageID _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Protocol.MessageID ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private Protocol.MessageRetCode _RetCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Protocol.MessageRetCode RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private string _Auth;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Auth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Auth
    {
      get { return _Auth; }
      set { _Auth = value; }
    }
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageHeart")]
  public partial class MessageHeart : global::ProtoBuf.IExtensible
  {
    public MessageHeart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}